language: php

matrix:
  fast_finish: true
  include:
    - 7.0
    - 7.1
    - 7.2
    - nightly
  allow_failures:
    - php: nigthly

install:
  - composer update --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs -np --colors

after_success:
  - bash <(curl -s https://codecov.io/bash)
